---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(shiny)



data(nyc_airbnb)

nyc_airbnb

nyc_airbnb = 
  nyc_airbnb %>% 
    mutate(stars = review_scores_location / 2) %>% 
    rename(borough = neighbourhood_group) %>% 
    select(borough, neighbourhood, stars, price, room_type, lat, long) %>% 
    drop_na(stars)
  
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boroughs = nyc_airbnb %>% distinct(borough) %>% pull()
max_price = 1000
min_price = nyc_airbnb %>% distinct(price) %>% min()
room_choice = nyc_airbnb %>% distinct(room_type) %>% pull()


selectInput(
  inputId = "borough_choice",
  label = "Borough Choice",
  choices = boroughs
)

sliderInput(
  inputId = "price_range",
  label = h3("Price Range"),
  min = min_price, max = max_price, value = c(100, 250)
)

radioButtons(
  inputId = "room_choice",
  label = h3("Room Type"),
  choices = room_choice
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  nyc_airbnb %>% 
  filter(borough == input[["borough_choice"]],
         price >= input[["price_range"]][1],
         price <= input[["price_range"]][2],
         room_type == input[["room_choice"]]) %>% 
  plot_ly(x = ~lat, y = ~long, color = ~price,
          type = "scatter", mode = "markers", alpha = .5)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  nyc_airbnb %>%
  filter(
    borough == input$borough_choice, 
    price %in% input$price_range[1]:input$price_range[2],
    room_type == input$room_choice) %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', stars)) %>% 
  plot_ly(
    x = ~long, y = ~lat, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~price, text = ~text_label)
})

```

### Chart C

```{r}
renderPrint({
  input[["room_choice"]]
})
```

